# Generated by Django 5.0.2 on 2025-04-01 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('format', models.CharField(max_length=10)),
                ('quality', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('is_playlist', models.BooleanField(default=False)),
                ('playlist_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
